# Dependencies
markdown:	kramdown
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		journal | madebychip
tagline:	'blog'
description:	'My design journal'
url:		http://journal.madebychip.com
commentsystem:	google
disqus:		madebychip
color: '#589FF1'

author:
  name:		'Chip Dong lim'
  url:		http://madebychip.com

paginate:	3

# Custom vars
icon:		/assets/images/icon.png
profile:   /assets/images/profile.jpg
cover:		/assets/images/cover.jpg
color: ''

social:
  - icon:	twitter
    url:	https://twitter.com/lcdvirgo
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/lcdvirgo
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	http://plus.google.com/u/0/104292088680089345189
    desc:	Add me on google+

  # - icon:	feed
  # url:	http://camporez.com/atom.xml
  #  desc:	Inscreva-se no meu feed
    
menu:
  - title:	Portfolio
    url:	http://madebychip.com
    
  - title:	About
    url:	blog/hello-world/


copyright:
  author:	Chip Dong Lim
  url:		http://madebychip.com
  #type_title:	Alguns direitos reservados
  #type_url:	http://creativecommons.org/licenses/by-nc/2.5/br
